### ISSUE TITLE
Q: batching assumption

### ISSUE THREAD

**Issue by jardakotesovec** [facebook/dataloader#1]
@leebyron this lib looks great, thanks for sharing!

Is my assumption correct that dataloader batches requests within one event loop and send request to db on nextTick or something? I guess its only way to say when batching is finished. 

If so, maybe would be good to explicitly mention that in docs as it can get important when designing backend flow.

Lets say that I have sql backend without parallelize - it seems that in that case it still might make sense to batch sql queries there, so they resolve at the same event loop, therefore they have higher chance to batch together in subsequent queries and result in less requests. Does that sounds like reasonable thought process? :-)

**Comment by acdlite** [comment]
You are correct: https://github.com/facebook/dataloader/blob/master/src/index.js#L156-L158

> DataLoader batches all loads which occur in a single frame of execution, but should include in the batch all loads which occur during the flushing of the "PromiseJobs" JobQueue after that same execution frame.

**Comment by leebyron** [comment]
Thanks for the feedback! I'll clarify in the readme

**Comment by tonyxiao** [comment]
are there other ways in which we can configure the batching? Say within 1000 milliseconds rather than 1 event loop?
