### ISSUE TITLE
Client-side support?

### ISSUE THREAD

**Issue by BnayaZil** [facebook/dataloader#101]
Is this library should work in client-side?
I saw the library use `process.nextTick(...)` but I start to implement the library in my client-side code and I got no errors, which is weird.

**Comment by nvartolomei** [comment]
Probably you have a [`process` shim](https://www.npmjs.com/package/process) included, via other library or by a bundler like browserify.

**Comment by BnayaZil** [comment]
@nvartolomei thanks, now I see that [Webpack mocks process object](https://webpack.js.org/configuration/node/#node-process)
