### ISSUE TITLE
Dataloader methods require binding to be chained

### ISSUE THREAD

**Issue by justinanastos** [facebook/dataloader#102]
Example:

```
const loader = new DataLoader( ... );

// Throws error because `this._promiseCache` can't be found
Promise.resolve().then(loader.clearAll);

// Works
Promise.resolve().then(loader.clearAll.bind(loader.clearAll));
```

This will fail because `clearAll` needs access to `this`.

Proposal: Bind all instance methods in `DataLoader` constructor.

**Comment by wincent** [comment]
An alternative to consider that is terser than `bind`:

```
Promise.resolve().then(() => loader.clearAll());
```

It's a fairly common idiom to *not* bind methods by default in ES6 classes — one of the "joys" of JS that most JS programmers are familiar with — so I'm a little hesitant to incur the cost of binding everything preemptively when I suspect it is relatively rare for people to pass around instance functions in the way that you have above.

**Comment by justinanastos** [comment]
> It's a fairly common idiom to not bind methods by default in ES6 classes

That's true for the most case. In this case, the functions in dataloader require access to `this`, so by *not* binding them they are open to being called in a way other than was intended.

>I'm a little hesitant to incur the cost

While this will happen every time time a new dataloader is instantiated, per-request for 5 loaders in my case. I guess that could be more substantial with more loaders and apparently no one has tried to use dataloader this way.

## Another Option

I could add a configuration option to require an opt-in to autobinding; then the cost would only be paid when the user explicitly requests it. Thoughts?

**Comment by wincent** [comment]
> While this will happen every time time a new dataloader is instantiated, per-request for 5 loaders in my case. I guess that could be more substantial with more loaders and apparently no one has tried to use dataloader this way.

Well the trade off is the unavoidable `bind` vs the as-needed opt-in creation of the arrow functions. I wouldn't say that nobody has tried to do this, just that I expect that they probably just used an arrow function and moved on. Especially in the concrete example of `clearAll`, consider that it *is* very common to just discard the instance at the end of each request and let it get cleaned up by the garbage collector, so most people probably aren't even calling it at all. (Same for `clear`, both of which are [described as "certain uncommon cases" in the README](https://github.com/facebook/dataloader#clearing-cache).)
