### ISSUE TITLE
[Question] Does it make sense to throw error on key/value constraint mismatch?

### ISSUE THREAD

**Issue by etyp** [facebook/dataloader#104]
I was working through adding dataloader to a few heavier GraphQL endpoints (super valuable by the way, so thank you for your work on this), and was having issues with mismatched data that I only caught by chance.

It turns out that I was running into one of the two [constraints mentioned on the batch function](https://github.com/facebook/dataloader#batch-function).

I'm wondering if it might make sense (or if it's even possible) to throw an error or warning when either of the following two constraints is not withheld:

- The Array of values must be the same length as the Array of keys.
- Each index in the Array of values must correspond to the same index in the Array of keys.

**Comment by kolpav** [comment]
> The Array of values must be the same length as the Array of keys

`TypeError` for it is already thrown [here](https://github.com/facebook/dataloader/blob/master/src/index.js#L272-L281)

> Each index in the Array of values must correspond to the same index in the Array of keys

This one is impossible to check. It is up to you to make sure that your resolved values are in correct order.

If you are doing something like this
```javascript
const getUsersByIds = ids => UserModel.whereIn('id', ids)
```
`WEHER IN` is not returning rows in the same order as ids. So you have two options:

Sort them in memory
```javascript
const getUsersByIds = ids =>
  UserModel
    .whereIn('id', ids)
    .then(users => {
      const usersByIds = _.keyBy(users, 'id')
      return ids.map(id => usersByIds[id] || null)
    }))
```
Write SQL query in such a way that ordinality is assured
```sql
-- Postgres 9.4 or later
SELECT c.*
FROM   comments c
JOIN   unnest('{1,3,2,4}'::int[]) WITH ORDINALITY t(id, ord) USING (id)
ORDER  BY t.ord;
```
Taken from [here](https://stackoverflow.com/questions/866465/order-by-the-in-value-list)

**Comment by leebyron** [comment]
Great answer @kolpav
