### ISSUE TITLE
I rewrote this lib in reasonml

### ISSUE THREAD

**Issue by ulrikstrid** [facebook/dataloader#106]
I rewrote this lib for use with BuckleScript: https://github.com/ulrikstrid/bs-dataloader

My questions is, am I allowed to do this? And should I have the same license as you do?
It's not a 1 to 1 rewrite, but pretty much, I want the license to be as permissive as possible.

**Comment by wincent** [comment]
> My questions is, am I allowed to do this?

There are a few other implementations [listed in the README](https://github.com/facebook/dataloader#other-implementations). By chance, they look like they happen to use the MIT license. I'd say you'd be fine (and you should submit a PR to add your implementation to the list!).
