### ISSUE TITLE
Need advice on associations and priming

### ISSUE THREAD

**Issue by Togrias** [facebook/dataloader#108]
I need help figuring out how to set up dataloaders for associations.

Let's say I have the following database schema:
models: 
User, Photo,
associations:
User.Photos = User.hasMany(Photos)

If I set up a dataloader for User.Photos, then whenever I load User.Photos, I can also prime PhotoLoader with its results.
I.e.
results = await #some promise that batch loads User.Photos;
results.forEach(result => {result.forEach(row => {PhotoLoader.prime(row[foreignKey], row)})})

I'm creating a new set of dataloaders for each request.

Is this a good idea? What caveats do I have to take note of? What happens on mutations or fetching of other data/possibly other models or associations?

**Comment by kolpav** [comment]
IMHO I don't see anything wrong with priming as many loaders as you can with each trip to DB. As you said you need to be extra careful if you are mutating data during request which some other data depends on. You can then `prime` or `clear` mutated entities so your cached data reflect changes in DB.

One thing I would probably avoid is to store entities with their loaded relations.
```
{
  1: {
    username: "foo",
    photos: [
       {...},
        ...
       {...}
    ]
  }
}
```
I would store just the `users` and just the `photos` in theirs respective loader. Then have their associations as array of ids.
