### ISSUE TITLE
Support for multi-tenant architecture

### ISSUE THREAD

**Issue by aniyanm** [facebook/dataloader#114]
I am building a saas like application in which each tenant has their own tenant databases. I have graphql server at my backend and on each request, the tenant database is dynamically selected from tenant id passed in authorization headers. I would like to know how I can differentiate dataloaders for each tenant. Say I have userLoader, so I can use userLoader.load('12') to load user with id '12'. But this same id can be present across all my tenants. So please let me know how to implement dataloader in a multi-tenant architecture.

**Comment by alexisgahon** [comment]
@aniyanm You can instantiate one loader for each tenant.
It's up to you to set rules to handle the dispatch
```
userLoader.foo.load('12')
userLoader.bar.load('2')
```

**Comment by leebyron** [comment]
This library won't manage multi-tenancy for you, you'll need to write logic to handle that according to the specific rules you set up for that.

This library is single-focused on providing the decoupled batching behavior
