### ISSUE TITLE
Create docs for, or add feature to set cache timeout.

### ISSUE THREAD

**Issue by aconfee** [facebook/dataloader#128]
Hello!

Is there a cache timeout exposed? If not, what is the reason for that? What are best practices? Can this be documented, or the feature added, as it's an extremely common case. 

Thanks!
Adam

**Comment by kolpav** [comment]
You can do it like so:
```javascript
var userLoader = new DataLoader(...)
setTimeout(() => userLoader.clearAll(), 1000 * 60)
```
But the fact that you need something like this implies that your loaders are not short lived as in created and destroyed for each request. I am not saying its wrong but maybe your use case is more advanced in that case take a look at [custom caches](https://github.com/facebook/dataloader#custom-caches) section which gives you complete freedom in how should your underlying cache work.

**Comment by leebyron** [comment]
Definitely check out https://github.com/facebook/dataloader#custom-caches - you can supply whatever cache you like, including with timeout or LRU style eviction
