### ISSUE TITLE
exists(key)

### ISSUE THREAD

**Issue by ravilution** [facebook/dataloader#130]
Hi,

Can we add a function that checks if the cache has any object with the given key?

`
exists(key: K): boolean {
  return this._promiseCache.get(key) === undefined
}
`

**Comment by leebyron** [comment]
This is possible by passing a custom cache implementation when building your data loader which provides the capability - however cache availability is something DataLoader intends to be a hidden implementation detail.

If there's a critical workflow you're trying to enable, I think it would be more helpful to look at the intended use so we could look at all possible solutions, including exposing cache availability.
