### ISSUE TITLE
is loadAll operation outside of dataloader?

### ISSUE THREAD

**Issue by jepezi** [facebook/dataloader#14]
First, thanks for the great lib!

I'm learning how to use dataloader in Relay and I got it working with loading the singular object by id. Now I'm wondering if it's possible to use dataloader to do something like `lessonLoader.loadAll()` in my root "viewer" query? Not sure if it's a really stupid question and completely outside of this lib or should I do a 2-phase loading i.e. first query all ids from lessons table and then use loadMany afterwards?

**Comment by zuhair-naqvi** [comment]
@jepezi do you mind please sharing your learnings here?

**Comment by AlicanC** [comment]
On a root connection's resolve(), I just query the database for ids and return objects with only ids in them (`[{ id: 1 }, { id: 2 }, ...]`) and then in resolveNode() (where I receive those objects) I load the rest of the data with DataLoader.

At first, making two trips to the database (one trip for ids and another batched trip for complete data) seemed stupid, but if the ids are cached then the second trip doesn't happen at all and if they are not cached then you are caching them for use in another query.

The function I use to create root connections look like this:
```javascript
export function createRootConnectionField({ nodeType, tableName }) {
  const { connectionType } = connectionDefinitions({
    nodeType,
    resolveNode: (edge) => getDataLoaderOfType(nodeType).load(edge.node.id),
    connectionFields: () => ({
      totalCount: {
        type: GraphQLInt,
        resolve: (connection) => connection.totalCount,
      },
    }),
  });

  return {
    type: connectionType,
    args: connectionArgs,
    resolve: async (viewer, args) => {
      const objects = await db(tableName).select('id');

      return {
        ...connectionFromArray(objects, args),
        totalCount: objects.count,
      };
    },
  };
}
```

On the other hand, if your cache gets invalidated often, then you will be making two trips all the time and this becomes a performance issue. If that's the case then you could easily select all columns in resolve() and remove resolveNode(). If you do that, you might also want to prime the cache using dataLoader.prime(key, value) in your resolve().

**Comment by pedro-surf** [comment]
Why did you close it without a reference nor a comment? @AlicanC provided some good info about connections setup, however this didn't answer the question, for me, at least.

**Comment by jgcmarins** [comment]
ideally you should not "loadAll", but have a connection which knows how to load each individually
check this: https://github.com/entria/graphql-mongoose-loader/blob/master/src/ConnectionFromMongoCursor.ts
