### ISSUE TITLE
How long the cache will live as default and how do I change it ?

### ISSUE THREAD

**Issue by vianhanif** [facebook/dataloader#144]
Is this question already answered somewhere ?

Thanks

**Comment by alexeyraspopov** [comment]
There is no built-in logic that clears cache under some circumstances. However, there are [ways to use API](https://github.com/facebook/dataloader#clearing-cache) to clear cache that you can use in your application.

**Comment by tuananh** [comment]
@vianhanif or you can use custom cache like `lru-cache` https://github.com/facebook/dataloader#custom-caches
