### ISSUE TITLE
function did not return a Promise of an Array of the same length as the Array of keys

### ISSUE THREAD

**Issue by tuananh** [facebook/dataloader#148]
i have a simple sql select whereIn for batching fn.

```js
mysql('mytable').select().whereIn('id', ids)
```

However, if one of the id doesn't exist, this error will be thrown

```
DataLoader must be constructed with a function which accepts Array<key> and returns Promise<Array<value>>, but the function did not return a Promise of an Array of the same length as the Array of keys.
```

I understand the error but not sure how to fix it in this case.

**Comment by tuananh** [comment]
never mind, i found the example which works for this case. Should have read the docs first.

**Comment by UmerIftikhar** [comment]
can you share the solution, I am also facing the same issue.
Thanks in advance.

**Comment by tuananh** [comment]
@UmerIftikhar in my case it was because some id doesn't exist in the database hence, the no. of rows return is less than the no. of input ids.

that's why i got

> did not return a Promise of an Array of the same length as the Array of keys.

What i did is create a map function to map the output. similar to the example here https://github.com/facebook/dataloader/blob/master/examples/Knex.md
