### ISSUE TITLE
Paginating with dataloader in this case

### ISSUE THREAD

**Issue by zefexdeveloper** [facebook/dataloader#160]
I have a case that is like this:

```
{
  author(id: 1) {
    books {
      id
      chapters {
        id
      }
    }
  }
}
```

If I don't use dataloader, this query would hit the database 502 times, one for the author, one for the book and 500 times if there's 500 books. I could use dataloader for that and it would use the `IN` clause in the SQL query and return all the results for me.

The problem: I was wondering, I want to implement the relay connections specification for pagination, where I need to specify things like `first`, `after` and other information for paginating. I was wondering, how can I solve this problem when using dataloader?

**Comment by jgcmarins** [comment]
check this: https://github.com/entria/graphql-dataloader-boilerplate

**Comment by zefexdeveloper** [comment]
@jgcmarins I did but you are solving it around a package called `@entria/graphql-mongoose-loader` but I'm not using mongodb, I'm using postgres with sequelize.

E viva o 🇧🇷

**Comment by jgcmarins** [comment]
Great!
But you could also do the same with Postgres. Follow this idea: https://github.com/entria/graphql-mongoose-loader/blob/master/src/ConnectionFromMongoCursor.js
We already have used the same approach with Postgres and Oracle, on production.
Works great. I'll take a look on what is missing for us to make those packages open source.

Viva 🇧🇷

**Comment by zefexdeveloper** [comment]
I will be reading the code, thank you for that.

Off: Tentei entrar em contato com você pelo twitter para tirar uma dúvida mas está fechado as mensagens, como posso entrar em contato direto com você para tentar lhe explicar o problema?

**Comment by jgcmarins** [comment]
> Off: Tentei entrar em contato com você pelo twitter para tirar uma dúvida mas está fechado as mensagens, como posso entrar em contato direto com você para tentar lhe explicar o problema?

Done
