### ISSUE TITLE
"maxBatchSize" question

### ISSUE THREAD

**Issue by j** [facebook/dataloader#172]
Without digging into the code too long, I'm wondering about the "maxBatchSize" option.

In MongoDB, I find that doing parallel finding in smaller batches is more performant than doing a huge query.  With that said, is "maxBatchSize" made to solve this use-case and will it resolve 1,000s of ids if maxBatchSize is set to 10 for example and does it process them in parallel?  Anything to keep in mind?

Docs are limited for this option and test case is tiny.

**Comment by jsphweid** [comment]
@j,

I was curious about this too and simply ran a quick test in my browser. It looks like it chunks up the requests and executes them all at once like Promise.all().

Upon execution, you all the chunks as pending requests which slowly get resolved. So yes the chunks / batches are run in parallel.

**Comment by j** [comment]
@jsphweid great!  thanks.
