### ISSUE TITLE
Handling fetch all

### ISSUE THREAD

**Issue by matthewmueller** [facebook/dataloader#22]
For the case of loading all rows from a table, you don't really care what the ID is, but you may want to cache all responses with their IDs for future requests. This would also be applicable when you have top-level queries

It might make sense for there to be a way to manually cache results.

**Comment by leebyron** [comment]
You should check out #18 which just landed. This lets you prime a cache. If you have another service which loads a list of things without knowing their keys first, then you could use `prime` to insert them into your dataloader cache.

**Comment by matthewmueller** [comment]
wonderful!
