### ISSUE TITLE
Incorrect logic?

### ISSUE THREAD

**Issue by gyzerok** [facebook/dataloader#3]
[Here](https://github.com/facebook/dataloader/blob/master/src/index.js#L77) is a confusing logic for understanding about dispatch necessity.

Shouldnt it be
```js
var needsDispatch = this._queue.length > 0;
```

Would be happy to make a PR if I'm right.

**Comment by leebyron** [comment]
The current logic is correct. I will clarify the comment above it to try to reduce confusion.

The idea here is that you want to schedule a dispatch of a queue when it changes from being empty to being full. This empty check is immediately before we call `_queue.push()` which changes the queue from empty to full.

If changes to a greater-than operation, the empty to full step would be missed, but also it would trigger a new dispatch as a queue went from full to "fuller" - e.g. each append to the queue would schedule a new dispatch, resulting in multiple dispatches of the same queue.
