### ISSUE TITLE
Distinct keys batching with cache disabled

### ISSUE THREAD

**Issue by alexandrebodin** [facebook/dataloader#34]
Hello guys.

This lib is very valuable ! great job

I am encountering an issue when calling the load function with the same key and having the cache disabled. I expected that batching would only call my getBatch with distinct keys but instead I got repeated keys.

This use case generate issues when selecting data in a DB and for example using a WHERE IN statement. 
It will only return one value if we pass the same key more than once but DataLoader will throw an exceptions.

I believe we could use a temp cache for batching to know if it is useful to add the same key loading to a batch without caching the promise.

I'd love to make a PR if everyone feels it's a good idea

What do you think ?

**Comment by leebyron** [comment]
I'm a little confused as to what you're proposing. Are you suggesting there is a bug, or that we should add new behavior?

Perhaps you could write some example code to illustrate what you want to do - how it behaves now - and how you want it to behave?

**Comment by alexandrebodin** [comment]
Hi Here is a more concrete example: https://gist.github.com/alexandrebodin/6e43012234abafceb6437051c8cca141

**Comment by alexandrebodin** [comment]
Hi,

I have drafted a first pull request #44  for review and discussion.

**Comment by nicksrandall** [comment]
I have implemented #46 in my implementation of dataloaders in Golang and it has been very useful.
