### ISSUE TITLE
Port of DataLoader for Java and Vert.x now available

### ISSUE THREAD

**Issue by aschrijver** [facebook/dataloader#36]
I have created a port of `DataLoader` for use with Java 8 and Vert.x.
Its still a work-in-progress, but you can check it out at: 

https://github.com/engagingspaces/vertx-dataloader

**Comment by leebyron** [comment]
Very awesome!

**Comment by bbakerman** [comment]
Also available in a pure Java 8 form as https://github.com/graphql-java/java-dataloader/

**Comment by aschrijver** [comment]
Yes, the fork @bbakerman made from `vertx-dataloader` to make it independent of Vert.x should be considered the official version and the way to go.

I added a note of this nature at the top of the README some time ago. Though you could still use the Vert.x version, I do not actively maintain it anymore.
