### ISSUE TITLE
Promise.all(...load) returns different order when batched

### ISSUE THREAD

**Issue by ericclemmons** [facebook/dataloader#37]
- `node@6.3.0`
- `npm@3.10.3`
- `dataloader@1.2.0`

Given the following GraphQL resolver that does a `Promise.all` on several `loader.load(id)` calls:

```js
/**
 * GraphQL resolver that, given an ugly "posts" feed fetches
 * the pretty version from a loader.
 */
posts(ugly, args, context) {
  console.log("ugly", ugly.posts.map((post) => post.id));
  
  // Wait on all posts to load from the prettier source
  return Promise.all(
    ugly.posts.map((post) => loader.load(post.id))
  ).then((posts) => {
    console.log("pretty", posts.map((post) => post.id));

    return posts;
  });
},
```

When `batch: false`, the result is correct:

```js
// ugly [ 7, 82, 102, 9, 11, 6, 201, 22, 75, 327 ]
// pretty [ 7, 82, 102, 9, 11, 6, 201, 22, 75, 327 ]
```

However, when `batch: true`, the output is somehow ordered:

```js
// ugly [ 7, 82, 102, 9, 11, 6, 201, 22, 75, 327 ]
// pretty [ 6, 7, 9, 11, 22, 75, 82, 102, 201, 327 ]
```

(Note that the value of `cache` has no impact on this whatsoever).

I couldn't find any place in the code that ordering occurs based off of `batch`.

This behavior is worrisome as it doesn't match expectations with example code:

```js
var [ a, b ] = await Promise.all([
  myLoader.load('a'),
  myLoader.load('b')
]);
```

**Comment by ericclemmons** [comment]
Ah, ok. Simple dilemma, simple solution: **ensure that the `batchedFn` provided in the constructor sorts results to match the passed in `keys`**.

By default, it seems MySQL returns rows sorted by `id` when no `sort` has been provided.

When `batch: true`, these IDs are fetched in bulk (and sorted by MySQL) vs. when `batch: false`, the IDs are fetched _individually_, so they return their original order.

Thanks for being here to talk it out :D

**Comment by leebyron** [comment]
Haha, glad you resolved this. Yes, it is important that your batch loader maintain this order.
