### ISSUE TITLE
Confusion about key.length === value.length

### ISSUE THREAD

**Issue by Naoto-Ida** [facebook/dataloader#40]
So I have been writing a GraphQL API and loving it!
We have run into an N+1 issue, and after watching Lee's video,
we have decided to try out Dataloader.

[Here](https://github.com/facebook/dataloader/blob/master/src/index.js#L250) there is an error about the key length and value length matching.

Say for instance we have an `ArtistType`. An `ArtistType` has a `GraphQLList` of `ArticleType`.
```js
// ArtistType
export default new GraphQLObjectType({
	name: 'Artist',
	fields: () => ({
                ...
                articles: {
                       type: new GraphQLList(ArticleType),
                       resolve: (artist, args, ast, { rootValue }) =>  {
                               return ArtistArticlesLoader.load(artist.id)
                       }
                }
        })
})

```

My dataloader is something similar to this (note that I'm using [Sequelize](http://docs.sequelizejs.com/en/v3/):
```js
export const ArtistArticlesLoader = new DataLoader((ids) => new Promise((resolve, reject) => {
	sequelizeDB.query(
		`SELECT a2.*
                  FROM ARTIST a1
                  LEFT JOIN ARTICLES a2 ON a2.subjectId = a1.id
                  WHERE a1.id IN (:ids)`,
		{
                        type: Sequelize.QueryTypes.SELECT,
                        replacements: {
                        	ids: ids
                        },
                        raw: true
		}
	).then((results) => {
		let res = results.map(result => {
			return {
				...result
			}
		})
		resolve(res)
	)
}))
```

Let's say I throw a query like this:

```
query {
    artists {
        articles {
            title
        }
    }
}
```

Now since Artists' Articles are `m:n`, the keys and values lengths don't match and I'm getting that error.
Am I using this in the wrong way?
I've checked out examples like [this](http://gajus.com/blog/9/using-dataloader-to-batch-requests), but don't know how the lengths match..

**Comment by helfer** [comment]
@Naoto-Ida yeah, you're not using it as intended. In your case, you're giving it a list of Artist IDs, and you're getting back a list of Article IDs for **all** of those artists mixed. You can either fetch articles by article ID, or do the batching/caching to fetch all articles for an artist **per** artist, in which case you would return not a list of articles, but a list of lists of articles, i.e. [[article1, article2, ...]]

**Comment by Naoto-Ida** [comment]
@helfer Thanks for the clarification!

I also have other types that contain an `articles` field.

So now I've made these loaders:
```js
export const ArtistArticleIdsLoader = new DataLoader((ids) => new Promise((resolve, reject) => {
    DOQUERYTOGETARTICLEIDS.then((results) => {
        let res = results.map(result => result.id)
        resolve(res)
    )
}))

export const EventArticleIdsLoader = new DataLoader((ids) => new Promise((resolve, reject) => {
    DOQUERYTOGETARTICLEIDS.then((results) => {
        let res = results.map(result => result.id)
        resolve(res)
    )
}))

export const ArticleLoader = new DataLoader((ids) => new Promise((resolve, reject) => {
    DOQUERYTOGETARTICLES.then((results) => {
        resolve(results)
    )
}))
```

Then in the `ArtistType`:

```js
export default new GraphQLObjectType({
    name: 'Artist',
    fields: () => ({
                ...
                articles: {
                       type: new GraphQLList(ArticleType),
                       resolve: (artist, args, ast, { rootValue }) =>  {
                               return ArtistArticleIdsLoader.load(artist.id)
                              .then((articleIds) => {
                                      const promises = articleIds.map(id => ArticleLoader.load(id))
                                      return Promise.all(promises).then(results => results})
                              })
                       }
                }
        })
})
```

The first two loaders bunch up the ids of articles associated to a certain Artist or Event,
the last loader bunches up the results for those articles.
