### ISSUE TITLE
Flow support

### ISSUE THREAD

**Issue by tompiarulli** [facebook/dataloader#45]
This library compiles itself into dist/index.js using Babel which strips out the Flow annotations, but what about those of us using this in a flowtyped project that are using babel to compile later down the line? Is there any way to get autocompletion/type checks? 

The only thing I can think of is writing a separate flowtype interface file and including it in my project, but given the definitions are already written it seems like there should be a way to load them from the node module.

**Comment by leebyron** [comment]
Yeah, let's get a flow type file directly into the npm bundle. The Flow team is working on better tools for this, but I think we have a workaround to use in the meantime that should work just fine.

**Comment by wbyoung** [comment]
@leebyron I just discovered this myself. Thanks for responding so quickly to the original question and getting a PR merged. Any releases planned soon that would include this?

**Comment by dpnova** [comment]
Sorry @leebyron you mentioned a workaround... is there some more information about that? I'm currently using create-stub in flowtyped to create stubs for libs like dataloader that already have type annotations...
