### ISSUE TITLE
Cache expiration

### ISSUE THREAD

**Issue by tomitrescak** [facebook/dataloader#47]
Hi, is it possible to set the interval after which data shoukd be purged from the cache?
Thanks

**Comment by alexandrebodin** [comment]
Hi @tomitrescak 

From my perspective DataLoader is though out to have a naive use of cache.

Moreover `dataloader` provides a `cacheMap` configuration to pass your own cache implementation. For example a lru-cache or a ttl-cache based.

The decision would be yours ;)

**Comment by tomitrescak** [comment]
That makes perfect sense. Thanks.

**Comment by andyrichardson** [comment]
For anyone looking for a barebones TTL cache for use with dataloader - [here's a gist](https://gist.github.com/andyrichardson/1f4c6ac20189185443c123a406b848e6)

**Comment by alexstrat** [comment]
This NPM module is also a good option: [`expiry-map`](https://www.npmjs.com/package/expiry-map).
