### ISSUE TITLE
Duplicate keys in "IN", relational calls

### ISSUE THREAD

**Issue by Epenance** [facebook/dataloader#49]
Hi there,

I'm currently working on a GraphQL version of our API and i must say its a joy to work with your dataloader, however i just recently noticed that its not deduplicating keys in my "IN" select, possibly making my database look up the same thing 18 times and probably comparing it each time.

As an example I'm trying to pull out 18 cases from our database, each of them with a customer attached.

The SQL that gets executed looks like this:

``` sql
SELECT "company_name" AS "company", "customer_id" AS "id", "company_name" AS "company", "unik_id" AS "APIKey" FROM "complex_modules_realtor_customer_settings" AS "customer" WHERE "customer"."customer_id" IN (810, 810, 810, 810, 810, 810, 810, 810, 810, 810, 810, 810, 810, 810, 810, 810, 810, 810);
```

Rather than just :

``` sql
SELECT "company_name" AS "company", "customer_id" AS "id", "company_name" AS "company", "unik_id" AS "APIKey" FROM "complex_modules_realtor_customer_settings" AS "customer" WHERE "customer"."customer_id" IN (810);
```

Is this intentional or maybe im doing something wrong? (I'm using sequelize and graphql-sequelize so help me out).

**Comment by alexandrebodin** [comment]
@Epenance Do you have cache disabled ? 

If so we are currently discussing some changes that match your needs at #44

**Comment by eugene1g** [comment]
Not sure about `graphql-sequelize`, but I handle this in the resolver function with something like this -
```
import keyBy from 'lodash/keyBy'
import uniq from 'lodash/uniq'
import squel form 'squel'
import pg from 'pg-promise'
//...
const loadRecords = async (askedKeys) => {
  const query = squel.select().from('person').where('id in ?', uniq(askedKeys)).toString()
  const dbRows = await pg.any(query)
  const byId = keyBy(dbRows, row => row.id)
  return askedKeys.map(id => byId[ id ] || null)
}

const myLoader = new DataLoader(loadRecords)
```

This approach works, however #46 is neater because it handles race condition better.

**Comment by leebyron** [comment]
Closing this aging issue

I'll work on getting #46 polished up and ready to land since that would fix this issue, though I encourage either not turning off caching or doing this deduping within your batch function.
