### ISSUE TITLE
index.d.ts file is not installed from npm.

### ISSUE THREAD

**Issue by ovrmrw** [facebook/dataloader#54]
Even though there is a typed file (./src/index.d.ts), it is not installed via `npm install dataloader` command.

**Comment by Knaackee** [comment]
Any news? I cant find the type definition in the package.

**Comment by rcsole** [comment]
Same for `index.js.flow`!

**Comment by JacobSoderblom** [comment]
One way to solve it is to make an PR to DefinitelyTyped and add the type definition. In that way we will be able to install the type definition through `npm install @types/dataloader`.

**Comment by blakeembrey** [comment]
Actually, the current definition in this module is incorrect. It needs https://github.com/facebook/dataloader/pull/51 first.

**Comment by leebyron** [comment]
This is because a new release wasn't published after typings were added. I'll get a new release out pronto
