### ISSUE TITLE
Implementation in Golang

### ISSUE THREAD

**Issue by nicksrandall** [facebook/dataloader#59]
I have a WIP implementation in Golang.

The concurrency/async primitives in JavaScript don't translate very well to Golang but I have done my best to take the core themes of DataLoader and implement them in Go.

I would love to get feedback from others who are familiar with Golang and DataLoader so I'm posting this here to solicit feedback.

https://github.com/nicksrandall/dataloader

**Comment by nicksrandall** [comment]
One of my questions about this implementation is whether or not I should guarantee that the keys passed to the batchFn are unique. JavaScript has the ability to read the value from a resolved promise N number of times. So a JS implementation could cache a promise before it is resolved and then send that promise when a duplicate key is asked for. Thus guaranteeing that only unique keys get passed to batchFn. (I've seen a the PR for this).

This implementation uses go channels to communicate future values and those are read once. So, if a user asked for a duplicate key before the first key could be resolved, both (duplicate) values are sent to batchFn. is that acceptable? Is there a better way?

**Comment by nicksrandall** [comment]
My initial thought is that a user will probably want to choose (based on the nature of their data) if they want the assurance of unique keys getting passed to their batchFh. What I have done is is write a simple `UniqueBatchFunc` function that a user can use to wrap a batchFn which will unique the keys coming in and distribute the resulting data out to all the keys. 

In JavaScript it would look something like this: 
```js
function uniqueBatchFn(batchFn) {
  return (keys) => {
    const dict = {};
    const position = [];
    const uniqueKeys = [];
    const idx = 0;

    for (let i=0; i < keys.length; i++ {
      if (dict[keys[i]]) {
        dict[key] = i;
        position.push([i]);
        uniqueKeys.push(keys[i]);
        idx++
      } else {
        position[dict[keys[i]]].push(i);
      }
    }

    return batchFn(uniqueKeys).then((values) => {
      const out = [];
      for (let i=0; i < position.length; i++) {
        for (let j=0; j < position[i]; j++) {
          out.push(values[i]);
        }
      }
      return out
    });
  }
}
```

**Comment by sibelius** [comment]
ask from feedback on graphql.slack as well

**Comment by leebyron** [comment]
Nice work!

I'm definitely no Go expert, so I'll close this issue, but I'm glad to see your effort on bringing this idea to more environments.
