### ISSUE TITLE
Expose list of keys that are cached by a loader

### ISSUE THREAD

**Issue by Dashed** [facebook/dataloader#6]
```js
// naive cache invalidation strategy

myLoader.clearAll();
myLoader.loadMany([1, 2, 3]); // list of keys is computed

// ... later
myLoader.clearAll();
myLoader.loadMany([2, 3, 4]); // compute new list of keys
```

The list of keys that are loaded would need to be tracked externally to determine the set of keys to clear:
```js
// want to get this:
[1, 2, 3] \ [2, 3, 4] = [1]
```

For this to work, `this._promiseCache` would need to be officially exposed (e.g `.cachedKeys()`).

 Thoughts?

**Comment by leebyron** [comment]
I definitely think this should remain an implementation detail. In systems I've worked with before where the cache exposes this sort of thing, usually bad behavior starts to occur like checking caches before fetching which can cause race conditions and convoluted logic.

I don't fully understand your motivation for exposing the cache's state though, from a higher level what exactly is it that you would like to do that you can't do today? Smarter cache invalidation?

**Comment by leebyron** [comment]
While I still think it's probably a bad idea to sniff existence in your caches to drive logic, it's now possible by providing a custom cache.

**Comment by Dashed** [comment]
Thanks. I think custom caching is a good compromise. :+1:
