### ISSUE TITLE
Question: Does async/await remove the benefits of DataLoader?

### ISSUE THREAD

**Issue by ashah888** [facebook/dataloader#60]
In my implementation of GraphQL & DataLoader, I often use async/await to get the result of a database query. Then I pass the result into a model where I control the ACL (access control).

By doing this, does it remove the benefits of DataLoader? i.e. am I waiting for each DataLoader query to finish one-by-one by doing async/await on every query? I ask because if I don't do async/await and return a promise as an output (without my model ACL layer), the GraphQL APIs continue to work, I'd like to know if my usage of the ACL model is eliminating the benefits of DataLoader..

**Comment by leebyron** [comment]
Just to follow up on this: async/await not only does not remove the benefits of DataLoader, it's actually a quite nice way to use DataLoader. async/await is a syntactic way to operate on Promises, and Promises are returned by the load() function.

**Comment by matthewgertner** [comment]
@leebyron My colleague made a similar point to me. Presumably one major advantage of DataLoader is that it batches `load` calls when the occur on the same tick. If you say something like:

```
const foo = await dataLoader.load(...)
const bar = await dataLoader.load(...)
const baz = await dataLoader.load(...)
```

...then Node will execute each call in a separate tick and no batching will be possible (at least this is my understanding).

Am I misunderstanding something or do you just think that the convenience of `await` outweighs the benefits of batching?

**Comment by wincent** [comment]
@matthewgertner: Your understanding is correct. If you want the three loads to occur concurrently you will have to avoid the serial execution ordering that `await` imposes. In your example, you could use `Promise.all`:

```
const [foo, bar, baz] = await Promise.all([
  dataLoader.load(...),
  dataLoader.load(...),
  dataLoader.load(...),
]);
```

Note that this doesn't mean you can't use `await` at all, just that you have to be selective where and how you use it.

**Comment by matthewgertner** [comment]
Right, thanks for the clarification.

**Comment by drodil** [comment]
Commenting this old issue I found. How about if you have your own function for example:

```ts
const load = async (key: string) => {
  return dataloader.load(key);
}

await load('abc');
await load('def');
```

Is there any way to batch those two loads?
