### ISSUE TITLE
manually clear key when Transient Errors encounted? 

### ISSUE THREAD

**Issue by luckydrq** [facebook/dataloader#61]
The README says:

>Transient Errors: A load may fail because it simply can't be loaded (a permanent issue) or it may fail because of a transient issue such as a down database or network issue. For transient errors, clear the cache:

and gives an code snippet on how to deal with this situation:
```js
userLoader.load(1).catch(error => {
  if (/* determine if error is transient */) {
    userLoader.clear(1);
  }
  throw error;
});
```

It is recommended to do `clear(key)` manually. But after i read the code, it seems that [DataLoader already take care of this](https://github.com/facebook/dataloader/blob/master/src/index.js#L292). Am i missing something   or the doc need to update?

**Comment by ThisIsMissEm** [comment]
It'd seem so; I think the docs probably need to be updated.

**Comment by leebyron** [comment]
I just made some updates to Readme that hopefully improve this. Your suggestion is half-correct. If the entire batch request fails, then cache is cleared. If individual values are provided `Error`, those are cached. I updated the language to make this clear.

**Comment by luckydrq** [comment]
Thanks, i got your point. 

However, in real world from what i see, it rarely happens when `individual values are provided Error`, because batch function is designed to reduce network cost of fetching data to backend. For example, a batch function to load data from a rational database may look like this:
```js
var batchFn = ids => {
  return new Promise((resolve, reject) => {
    sqlRun(`SELECT * FROM user_table WHERE ID IN (${ids.join(',')})`, (err, records) => {
      if (err) {
        return reject(err);
      } else {
        return resolve(records);
      }
    });  
  });
};
```

rather than

```js
var batchFn = ids => {
  return Promise.all(ids.map(id => {
    return new Promise((resolve, reject) => {
      sqlRun(`SELECT * FROM user_table WHERE id=${id}`, (err, record) => {
        if (err) {
          return reject(err);
        } else {
          return resolve(record);
        }
      });
    });
  }));
}
```

**Comment by leebyron** [comment]
It certainly depends on the system you're communicating with, and of course it's up to how you implement your batching function. There is of course the case where the batch itself fails, which is well illustrated by your first example. There is also a case where your batch function may return a combination of values and errors. That is - the batch load itself succeeded however some of the individual operations within the batch failed.

**Comment by luckydrq** [comment]
Agreed, just to share my thoughts, thanks!
