### ISSUE TITLE
DataLoader doesn't seem to be clearing cache

### ISSUE THREAD

**Issue by lucasbento** [facebook/dataloader#65]
I noticed that GraphQL hasn't been updating a few records, after some digging I tried to use `clear()` and `clearAll()`, unfortunately none of them worked.

I use DataLoader as follows:
https://github.com/sibelius/graphql-dataloader-boilerplate/blob/master/src/loader/UserLoader.js#L21-L23

And a function for clearing DataLoader which is something like this:
```js
static clearCache(id) {
  return User.userLoader.clear(id.toString());
}
```
The `.toString()` function is because sometimes the `id` passed is a Mongoose ObjectId, which I also thought that could be a problem so I tried instantiating DataLoader like this:
 
```js
static orderLoader = new DataLoader(
    async ids => Promise.all(
      ids.map(id =>
        OrderModel.findOne({
          _id: id,
        }),
      ),
    ), { cacheKeyFn: key => key.toString() },
  );
```

Which also did not work.

I also have a few workers that updates records based on their statuses, so I need to call `UserLoader.clearCache(userId)` whenever I update an User record, the same goes for a mutation.

DataLoader cache works like a charm but it keeps hitting the cache after clearing, even using `clearAll()`, I'm not sure what the problem is.

**Comment by rturk** [comment]
Hi all any updates on this? I'm having similar issues

**Comment by ThisIsMissEm** [comment]
I'd take a guess that the issue you're seeing here is because you're sharing the dataloader instance between all your requests – instead, you should only use dataloader for a single requests' lifetime – otherwise you'll end up sharing data between requests.

The "workers", if running in a separate process, have a different instance of that dataloader.

That is, dataloader works entirely in memory: if you go to a different machine or different process, then you've a completely new dataloader instance. If your process restarts, same deal.

That is, dataloader really isn't much more than something like this:

```js
function createFetcher(fn) {
  var cache = {}

  return {
    fetch: function fetch(id) {
      if (!cache[id]) {
        cache[id] = fn(id);
      }

      return cache[id];
    },
    clear: function clear(id) {
      delete cache[id];
    }
}
```

(Sure, it uses process.nextTick to do batching, but the code above is meant to represent and show how it is in-memory)

**Comment by ThisIsMissEm** [comment]
See also #62

**Comment by leebyron** [comment]
@lucasbento - can you possibly replace your Mongo instance with some sort of mock so you can present the issue? I can't reproduce it, and we have tests that cover the clear functions that continue to pass.

My best guess from the information you shared is that you're using `userLoader.clear(id.toString());` while using `userLoader.load(id);` - if `id` is not already a string these will result in different keys, so `clear()` will be attempting to clear the wrong key.

I'm more confused by `clearAll()` not working. It's [implementation](https://github.com/facebook/dataloader/blob/master/src/index.js#L160) simply only calls `clear()` on the underlying cache `Map` instance. If you're not providing a custom implementation of `Map` (check your polyfills?) then perhaps something else is wrong with your application?

**Comment by lucasbento** [comment]
@leebyron: I'm gonna try to check what you just said, @ThisIsMissEm also has a good point, thank you both for answering.

I'm focusing on other projects right now so I don't really have enough time to work on this issue, I'm gonna try the suggestions as soon as I can, I'll close this issue for now and open again if needed.

Thank you!
