### ISSUE TITLE
Add option to skip cache if result not found

### ISSUE THREAD

**Issue by dcworldwide** [facebook/dataloader#69]
If you have the following events:

   DataLoader. load(1) // returns null
   Some code then inserts 1 
   DataLoader.load(1) // returns null, even though the record exists.

What to do here? Is there an elegant way to clear the cache for keys that returned null?

**Comment by ThisIsMissEm** [comment]
Do you do this in a single request lifecycle? If so, use `myLoader.clear(key)`, if you're sharing the dataloader instance between requests, see #62

**Comment by dcworldwide** [comment]
Yeah thanks. I've learned that I need to clear on mutation. Or...clear if load returns null.

**Comment by leebyron** [comment]
Typically returning `null` from a load implies that the value with that key is known not to exist, which is different from not being found, the first is a successful load (of an empty result) while the latter is an errored load. Cache behavior is key to this difference. For instance, if something is known not to exist, repeatedly fetching it would be unhelpful.

Having your batch function throw/return an Error when values have failed to load will ensure the cache is skipped.
