### ISSUE TITLE
Syntax errors in README

### ISSUE THREAD

**Issue by TomiBelan** [facebook/dataloader#7]
1) A comma and a colon are missing near here in the GraphQL example:

```js
      type: new GraphQLList(UserType)
      resolve (user, { first }) => queryLoader.load([
```

2) The last line of the Redis example `});` is missing one closing parenthesis.

3) This indentation is probably a mistake:

```js
      id => rows.find(
        row => row.id === id) || new Error(`Row not found: ${id}`
      )
```

**Comment by leebyron** [comment]
Thanks, next time feel free to open a pull request directly (you can do this by going to any file in github and clicking "edit")
