### ISSUE TITLE
LoadMany spawns Promise for each key

### ISSUE THREAD

**Issue by floatdrop** [facebook/dataloader#70]
Hi! Now `loadMany` calls `load` inside for each key which spawns lots of promises (it is cheap, but we spawning lots of them), but it can just return array from bulk function. Can/Should this be improved?

**Comment by leebyron** [comment]
I don't think this can be improved without shifting the cost of creating Promises elsewhere and complicating the codebase. `loadMany` needs to rely on the same cache as `load`.

I'm open to ideas or pull requests for improvement, but I would certainly request real performance numbers to support them. I would be surprised if the creation of Promises is a real bottleneck, but would be quick to act on real data if it proved to be.
