### ISSUE TITLE
I am having trouble wrapping my head around whether I need dataloader or not (posts & comments example).

### ISSUE THREAD

**Issue by booboothefool** [facebook/dataloader#77]
Besides  the good advice of "If you aren't sure you need it, you probably don't." 😅 

So let's say I have some typical posts and comments:

```
const POSTS_QUERY = gql`
  query Posts($cursor: String, $keyword: String, $order: Int) {
    posts(last: 10, before: $cursor, keyword: $keyword, order: $order) {
      feed {
        edges {
          cursor
          node {
            id
            author {
              objectID
              username
              avatar
            }
            text
            createdAt
            participantsCount
            commentsCount
          }
        }
        pageInfo {
          endCursor
          hasNextPage
        }
      }
    }
  }
`;
```

where you can * click on a post to see its comments * (query by `postId`)

```
const COMMENTS_QUERY = gql`
  query Comments($postId: ID!, $cursor: String) {
    comments(last: 10, postId: $postId, before: $cursor) {
      feed {
        edges {
          cursor
          node {
            id
            postId
            author {
              objectID
              username
              avatar
            }
            text
            createdAt
          }
        }
        pageInfo {
          endCursor
          hasNextPage
        }
      }
    }
  }
`;
```

And my resolver for a `posts` query looks something like:
```
  async getPosts(last: number, before: number, keyword: string, order: number): Promise<PostPage> {
    let result: PostPage;
    before = before || Date.now();
    keyword = `(?i).*${keyword}.*`;
    let ORDER = 'p.createdAt';
    let hottestAfter = 0;
    if (order === 0) {
      ORDER = 'commentsCount * participantsCount';
      hottestAfter = moment().subtract(2, 'weeks').valueOf();
    }

    try {
      const POSTS_QUERY = `
        MATCH (p:Post)<-[:AUTHOR]-(u:User)
        WHERE p.createdAt < { before } AND p.text =~ { keyword } AND p.createdAt > { hottestAfter }
        OPTIONAL MATCH (p)-[:HAS_COMMENT]->(c:Comment)<-[:AUTHOR]-(v:User)
        WITH p, u, count(DISTINCT v) as participantsCount, count(c) as commentsCount 
        ORDER BY ${ORDER} DESC
        RETURN collect(p {.*, author: u, participantsCount, commentsCount}) as posts
      `;

      const queryResult = await retryInterval(RETRY_COUNT, RETRY_INTERVAL, async (): Promise<object> => {
        const session = this.connector.session();
        try {
          const params: PostsQueryParams = {
            LIMIT,
            before,
            keyword,
            hottest,
          };
          const res = await session.run(POSTS_QUERY, params);
          return res;
        } catch (neo4jError) {
          throw new Error(neo4jError);
        } finally {
          session.close();
        }
      });

      // edges
      const posts: Array<object> = queryResult.records[0].get('posts');
      const edges: Array<Edge> = await Promise.all(
        posts.slice(0, last).map(async (post: PostNode): Promise<Edge> => {
          const cursor: number = post.createdAt;
          const hit = await usersIndex.getObject(post.author.properties.user_id, ['username', 'userPhotos']);
          const node: PostNode = {
            id: post.id,
            author: { 
              ...hit,
              avatar: _.get(hit, 'userPhotos[0].secure_url'),
            },
            text: post.text,
            createdAt: cursor,
            participantsCount: post.participantsCount,
            commentsCount: post.commentsCount,
          };
          return {
            cursor,
            node,
          };
        })
      );

     // pageInfo
      const endCursor: number | null = _.last(edges) && _.last(edges).cursor;
      const hasNextPage: boolean = !_.isEmpty(posts[first - 1]);
      const pageInfo: PageInfo = {
        endCursor,
        hasNextPage,
      };

      result = {
        feed: {
          edges,
          pageInfo,
        },
      };
    } catch (err) {
      console.error('(getPosts) =>\t', err);
    } 
    return result;
  }
```

^ Just to give the full picture, although `getComments` does something pretty similar, so it is omitted. 

I watched the following YouTube videos on the subject https://www.youtube.com/watch?v=OQTnXNCDywA & https://www.youtube.com/watch?v=UBGzsb2UkeY, but this does not seem to present a similar case. I'm trying to compare it to the "news feed example" and while I could potentially fetch the same user multiple times (e.g. the same user commented 20 times on a post), this is returned by `const hit = await usersIndex.getObject(post.author.properties.user_id, ['username', 'userPhotos']);`, which pulls the result from the Algolia index. On my own server however, it seems like this would really only be 1 request to get the `posts` + 1 request for that post's `comments`. So on the surface it does not seem like I would really need dataloader for this (it's not like the "news feed example" where there's users, then events, then users, then tags, then more users, users on users on users, unrelated users, etc... just simple posts & comments and who authored them), however I can only say so with 50% confidence and would really appreciate some advice, and questions I should be asking to properly make a decision.

Thanks!
-- Some dude building his first backend

**Comment by kolpav** [comment]
> Besides the good advice of "If you aren't sure you need it, you probably don't."

I think sooner or later you will need to use it. I am personally using it whenever I can. Usage is the same as in non batched/cached version of my call `ctx.models.User.getById(id)` vs `ctx.models.User.getByIds.load(id)` and I get all the benefits which go along with it. I create my DataLoaders on every request so I don't need to worry about clearing cache you just need to be careful to preserve order and number of resolved values. From your example `author` is good place where to use DataLoader.

> And my resolver for a posts query looks something like:

Your resolve function doesn't make sense to me. You are somehow resolving the entire sub-tree of node `feed` even when user didn't query for it. 
```graphql
const POSTS_QUERY = gql`
  query Posts($cursor: String, $keyword: String, $order: Int) {
    posts(first: 10, before: $cursor, keyword: $keyword, order: $order) {
      feed {
        edges {
          cursor
        }
      }
   }
}
```
would result in the exact same amout of queries/work.
Take a good look at [this](https://github.com/apollographql/GitHunt-API/tree/master/api) repo it is great reference on how you should structure/build your graphql backend.

**Comment by booboothefool** [comment]
@kolpav 

> Your resolve function doesn't make sense to me. You are somehow resolving the entire sub-tree of node feed even when user didn't query for it.

Woah, you're absolutely right. Thanks for pointing that out. That didn't even cross my mind. It was my first attempt at GraphQL cursor-based pagination using this article as reference: https://medium.com/@gethylgeorge/infinite-scrolling-in-react-using-apollo-and-react-virtualized-graphql-cursor-pagination-bf80617a8a1a and schema: https://github.com/Gethyl/GraphQLPagination/blob/master/graphql/Schema.js where it looks like they do the same thing...

```
  query Posts($cursor: String, $keyword: String, $order: Int) {
    posts(first: 10, before: $cursor, keyword: $keyword, order: $order) {
      feed {
        edges {
          cursor
        }
      }
   }
}
```

^ With the example query you provided, I don't now why anyone would ever do that without asking for the nodes and the pageInfo (as the entire purpose is to paginate on those edges and display those nodes). Now I'm actually even more confused because you're right, my resolver does indeed resolve that entire subtree even if you didn't ask for it, and now I don't know what a proper resolver for this would look like.

GitHunt's example uses offset-based pagination, which is much simpler than what I'm trying to do / what I need an example for. Otherwise, it has indeed been my go-to. 👍 

But anyway, pagination is an entirely different issue. Can you explain why it would be good to use dataloader with `author`? That part doesn't make sense to me. Are you saying that if I put this into a dataloader:

```
const hit = await usersIndex.getObject(post.author.properties.user_id, ['username', 'userPhotos']);
```

which is just a small part of `getPosts`, it will be able to batch just that specific part, and then `getPosts` as a whole will come back even faster? It does not seem like it would reduce the number of requests of my query `getPosts` and `usersIndex.getObject(...)` hits Algolia instead of direct requests to my server.

**Comment by kolpav** [comment]
> I don't now why anyone would ever do that without asking for the node and pageInfo

I don't think this should be your concern what someone might or might not query for
> now I don't know what a proper resolver for this would look like

I think main problem is you are thinking about it wrong, you are not resolving each query entire subtree you just need to resolve the immediate edge in each resolver (there might be exceptions to this). So in `posts(count: Int!): [Post]` you need to resolve JUST the `[Post]` type it can be as simple as `(_, { count }, ctx) => ctx.models.Post.getAllWithLimit(count)`, that's it.
If your `Post` type also have `author: User` well guess what you just need to resolve `User` type. Maybe like so `({ authorId }, _, ctx) => ctx.models.User.getById(authorId)`
```graphql
{
  posts(count: 10) {
    author {
      name
    }
  }
}
```
And that is perfect opportunity to use dataloader. 
`({ authorId }, _, ctx) => ctx.models.User.getByIds.load(authorId)` implementation for that might look something like this `const getByIds = ids => knex.from('user').whereIn('id', ids) // don't forget to ensure order and account for not found users` so instead of 10 separate queries to db you will get one.
