### ISSUE TITLE
Using DataLoader to batch queries with multiple parameters

### ISSUE THREAD

**Issue by gajus** [facebook/dataloader#78]
Using `DataLoader` to load data that is being looked up by PK (or other unique identifier) is straightforward.

What about more complex lookups?

Continuing with the example from an earlier [issue thread](https://github.com/facebook/dataloader/issues/58#issuecomment-292455540).

```graphql
{
  movies(date: "2017-04-06", coordinates: {latitude: 57.149911, longitude: -2.078433}, first: 3) {
    edges {
      node {
        venues(first: 10) {
          edges {
            node {
              events {
                id
              }
            }
          }
        }
      }
    }
  }
}

```

The reason batching of event lookup broke is because there is a non-batched query in the `Movie.venues` resolver:

```js
venues: async (parent: MovieRecordType, parameters: Object, context: ResolverContextType) => {
  // ...

  const locationMovieVenues = await getLocationMovieVenues(
    context.connection,
    parent.id,
    coordinates.latitude,
    coordinates.longitude,
    filterByDate,
    pagination.first + 1,
    afterDistance,
    afterVenueId
  );
```

The actual query is [rather complicated](https://gist.github.com/gajus/5dac5d01d0a4d261150fd35a5b874ffb#file-getlocationmovievenues-js-L4-L27).

Whats the proposed way to batch loading of a query as such?

**Comment by gajus** [comment]
I am considering of doing something along the lines of...

writing a thin-wrapper around `getLocationMovieVenues` using `DataLoader` that batches all requests into one, but continuing to call `getLocationMovieVenues` for each unique query combination. The benefit of this is that all lookups are done within the same event-cycle without complicating the query. The downside is that I'd still be sending multiple queries for what could be a single query.

**Comment by ivome** [comment]
You should be able to use the `cacheKeyFn` option for that. Then you could use the JSON serialized input arguments as cache key. That way, you have all the input arguments available in your `batchLoadFn` where you can implement the batching logic.

**Comment by kolpav** [comment]
Related to my #75

**Comment by gajus** [comment]
> You should be able to use the cacheKeyFn option for that. Then you could use the JSON serialized input arguments as cache key. That way, you have all the input arguments available in your batchLoadFn where you can implement the batching logic.

Thats exactly what I ended up doing.

**Comment by tuananh** [comment]
@gajus can you explain a bit more on what you ended up doing?

i get the part about the cache key fn but how do you batch sql queries with different params?

**Comment by gajus** [comment]
> how do you batch sql queries with different params?

That will entirely depend on the query. All you get is an array of objects describing the query parameters. How you construct the query using that array is up to you.

**Comment by tuananh** [comment]
@gajus i see.

so suppose if i need to batch request to load items from `items` table with different types (A and B), i will need to load them all using id `where in` and `type = 'A' or type = 'B'` ; and then group+filter them manually right?

**Comment by gajus** [comment]
> so suppose if i need to batch request to load items from items table with different types (A and B), i will need to load them all using id where in and type = 'A' or type = 'B' ; and then group+filter them manually right?

As an example, yeah.

It might also make sense to use UNION operator.

It depends what you are trying to cut.

In my case, a lot of the time I simply wanted to eliminate multiple roundtrips keeping the queries simple.
