### ISSUE TITLE
Dataloader in ruby

### ISSUE THREAD

**Issue by sheerun** [facebook/dataloader#80]
> If you port DataLoader to another language, please open an issue to include a link from this repository.

Sooo I've implemented a dataloader for ruby. It's not released yet, so I thought I could ask for feedback before it happens. Also ask where to post mentioned a link when the time comes :)

One confusing thing for me: what should happen when batch loader returns `nil` for some item? Should I reject promise? Or resolve with `nil`? Other than that, do you want suggest some more test cases? Thanks

https://github.com/sheerun/dataloader

**Comment by sheerun** [comment]
hmm?

**Comment by brysgo** [comment]
Not super familiar with the differences between dataloader and graphql-batch, could you elaborate?

**Comment by sheerun** [comment]
dataloader is more general than graphql-batch (it is based on promises that can be chained together, just like in dataloader. you don't need to use graphql gem at all to use it), has additional configuration options (cache, max_batch_size), and mostly api-compatible this this repository.

**Comment by brysgo** [comment]
Cool! I'm not working in Ruby ATM but I'll check it out next time I am.

**Comment by sheerun** [comment]
no problem. could you post a link from this repository?

**Comment by brysgo** [comment]
I'm not a contributor to dataloader, just an onlooker.

**Comment by wincent** [comment]
I had a very quick peek at your Ruby implementation. Looks nice. Feel free to submit a PR if you'd like us to add a link to it from the README (you'd need to add an "Other implementations" section near the bottom, after "Common Backends", I think).
