### ISSUE TITLE
Flow typed as `export default` but code as `module.exports`

### ISSUE THREAD

**Issue by yachaka** [facebook/dataloader#85]
Hi,

The flowtype for DataLoader is `export default class ...`, but in the code, the last line is `module.exports = exports['default'];`.

So in code we use `require('dataloader')`, but Flow expects `require('dataloader').default`. Using node v7.10.

Current workaround:
```js
const dataloader = require('dataloader');
const DataLoader = dataloader.default || dataloader; // So Flow doesn't print an error and the code runs fine
```

**Comment by albertorestifo** [comment]
I confirm and this is super-annnoying.

Maybe there is a possible workaround by defining a library file?
