### ISSUE TITLE
Confusion over type signature 

### ISSUE THREAD

**Issue by jamiehodge** [facebook/dataloader#87]
Would you please help me better understand the intentions behind the type signature and examples for this repo?

The return type of the loader is T | Error and all the examples return Error on not found. I have since followed this pattern. 

Similar to the pattern mentioned in the README, we have a set of repository objects that have a loader instance. Paginated list methods dereference IDs using the loader. 

Passing an Error up through a resolver typically does the "right thing": the graph returns a null and includes the error in its result. This doesn't work for relay connections, as the Error is treated as an object and the type resolver fails (in the case of a union). 

I currently check in the get by id method whether the result is an error, report the error and return null. This feels like unnecessary ceremony. 

Would one of you please explain what the intended pattern is/was, especially with regards to error handling? I'd really appreciate it.

**Comment by jamiehodge** [comment]
To put it more succinctly: why not treat the return value as an option type? Is not found an error?

**Comment by jamiehodge** [comment]
@wincent I'm still wrestling with this issue. Why does this library encourage treating not founds as errors and not simply return null? Is it considered exceptional that a requested ID is absent?

**Comment by wincent** [comment]
Remember that even though DataLoader was born in the context of GraphQL at Facebook, it tries to be general in nature and doesn't prescribe any GraphQL-specific semantics. It really is just a batching and caching mechanism.

As such, I think the main issue here is that choosing to return `null` is a "lossy" operation. There is no way to distinguish between `null`-meaning-a-record-definitely-does-not-exist, `null`-meaning-a-failure-occurred-trying-to-load-something, `null`-meaning-that-privacy-business-logic-prevented-the-load, `null`-meaning-something-else... Errors, on the other hand, have the ability to encode information about *why* the requested value isn't returned.

However, this discussion is pretty abstract. Might be interesting to explore some concrete aspects, like what exactly the pain points you experienced with Relay connections were; perhaps there's a mitigation that can be applied at that level.

**Comment by leebyron** [comment]
There's definitely a clear semantic difference between `Promise.resolve(null)` and `Promise.reject(new Error())` - dataloader seeks to preserve the difference, hence the return type.
