### ISSUE TITLE
Dataloader creating new instance.

### ISSUE THREAD

**Issue by masterSean** [facebook/dataloader#94]
I have a GraphQL endpoint which uses Dataloader, I placed the loaders on GraphQL context field so upon initiation its available on all resolver thru context arg, now I need a mutation which clears all of my Dataloader cache, and upon creating the mutation and logging the loaders thru the context arg, I was expecting that the cache is still present but It seems to create a new instance of my Dataloaders and all the cache data that I saw from the QraphQL query was not present and the "_promiseCache" is empty. I don't know whats wrong. I'm hoping someone could explain why its creating new instance of my Dataloaders.

![image](https://user-images.githubusercontent.com/11488853/28168407-9d08fa34-6811-11e7-9d78-80f6e49d15bf.png)

![image](https://user-images.githubusercontent.com/11488853/28168452-bfb204fe-6811-11e7-8b46-c936dc56bdf3.png)

**Comment by hamza-openinvest** [comment]
I'm not a dataloader contributor or expert, but I believe this is the expected behavior. According to https://github.com/facebook/dataloader#caching-per-request

> Typically, DataLoader instances are created when a Request begins, and are not used once the Request ends.

**Comment by wincent** [comment]
@hamza-openinvest is correct. Note that there is nothing *inside* DataLoader itself that enforces this; it's just a convention. Creating a new instance for every request and throwing it away at the end means that you don't have to worry about user-specific data leaking from one user to another. If you wanted to keep an instance (or instances) over a number of requests, then you'd either need to be operating in a context where there is no concept of "logged-in user" (or perhaps, one in which literally everything is public), or implement some higher-level orchestration that ensures that instances don't get shared across users.
