### ISSUE TITLE
Allow passing null as a dataloader key

### ISSUE THREAD

**Issue by alewaros** [facebook/dataloader#98]
The logic behind this is based simply on commodity when using multiple data loaders one behind the other. The reason why I'm not merging the batch function it's because some segments need caching and others should not have it. When loading many keys, some may resolve and other not as (square root) [16, 10, 9, 4, 1] => [4, null, 3, 2, 1] but I now want to apply another data loader the null value will throw an error, so I should filter invalid values in every step and somehow resort them at the end of all of them with a custom function.

My proposal is that instead of failing, it would just pass over the null values as (square root) [16, 10, 9, 4, 1] => [4, null, 3, 2, 1] => [2, null, null, null, 1]

While being consistent with load() which would just resolve as null => null

**Comment by aj-selina** [comment]
This was just a need I bumped into this week. I checked the code and the only change needed would be an if statement at the beginning of the load function.

```javascript
if (key == null) {
  return Promise.resolve(null)
}
```

I can make a PR, but would like a second opinion from a maintainer.

**Comment by leebyron** [comment]
Why should all Dataloaders have to conform that at key `null` is the value `null`? Others might want to treat this as an error. Others might not want to support it at all (programmer error). Also - for those using Dataloader along with Flow or Typescript, the introduction of `null` as a legitimate input and output value complicates things.

As a result, I think it's the right behavior to disallow by default, and allow a programmer who wants additional behavior to add that themselves.

I would strongly suggest checking for the `null` case *before* calling `load()`, so you can return whatever value or error makes the most sense for your application.

**Comment by joelgetaction** [comment]
@leebyron I would respectfully disagree - I think a `null` key mapping to `null` is by far the more common case and it should be the default behavior of `DataLoader` that `null` resolves to `null`.  Why?  Because if we have
```js
// parent table stores childId by GraphQL Parent returns Child entity
const parent = {
  childId: null
}

// Beautiful code if DataLoader accepts null ids or undefined ids
Parent {
  child: (parent, _, { loader }) => {
    return loader.findChildsByIds(parent.childId)
  }
}

// Much uglier and more verbose code if DataLoader barfs on null or undefined ids
Parent {
  child: (parent, _, { loader }) => {
    if (!parent.childId) {
      return null;
    }

    return loader.findChildsByIds(parent.childId)
  }
}
```
It is very common to signal "there's no child" by storing a `null` or `undefined` child id, and it seems that asking DataLoader for the entity corresponding to `null` is a reasonable thing that should return `null`.

I guess we don't want to break existing implementations that rely on `DataLoader` throwing on `null` or `undefined` ids.  Can you suggest a good work-around to have `DataLoader` return `null` for`null` or `undefined` ids without needing to monkey-patch `load` and `loadMany` and then risk breaking if `DataLoader` later expands its API surface?

**Comment by stewartmcgown** [comment]
For anyone using loaders in Node, specifically NestJS, I found a solution that works best for my use case (nullable many-to-one loaders). Hacky for now, but low complexity and can be done on a per-loader basis as opposed to monkey-patching the dataloader itself.

```ts
// @ts-ignore
  generateDataLoader(): DataLoader<string, Rider> {
    return getDataloader(async (keys) => {
      const jobs = await this.entityManager
        .getRepository(B2BDeliveryJob)
        .findByIds(keys as string[]);

      const ret: any[] = [];
      let jobIdx = 0;
      for (const key of keys) {
        if ((await key) === null) {
          ret.push(undefined);
        } else {
          ret.push(jobs[jobIdx]);
          jobIdx += 1;
        }
      }

      return ret;
    });
  }
...
```

Then when calling it from a resolver:

```ts
@ResolveField(() => B2BDeliveryJob)
  async b2bDeliveryJob(
    @Parent() order: Order,
    @Loader(B2BLoader) loader,
  ): Promise<B2BDeliveryJob | undefined> {
    return order.b2bDeliveryJobId
      ? loader.load(order.b2bDeliveryJobId)
      : loader.load(Promise.resolve(null));
  }
```

It may be a better idea to pre-filter keys before passing them to my ORM, but it looks like TypeORM just ignores ids that are malformed.
